language: minimal

services:
  - docker

env:
  global:
    - IMAGE_NAME=diuis/docker-emsdk-opencv4-wasm-custom

script:
  - docker build . -t "$IMAGE_NAME"

before_deploy:
  - docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_TAG}"

deploy:
  provider: script
  script: 
    docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TRAVIS_TAG}"
  skip_cleanup: true
  on:
    branch: master
    tags: true